### ISSUE TITLE
Backport the prismjs 1.27.0 upgrade to 3.x

### ISSUE THREAD

**Issue by stof** [wooorm/refractor#58]
react-syntax-highlighter is still using refractor 3 for now. As prismjs 1.27.0 fixes an XSS vulnerability, would you agree to backport that upgrade to a 3.x version of refractor ?

**Comment by wooorm** [comment]
- Where does it say there’s a security fix?
- Could it become acceptable to a) maintain an unmaintained project, or b) switch away from an unmaintained project?

**Comment by 72636c** [comment]
Here you go:

- https://github.com/PrismJS/prism/pull/3341
- https://security.snyk.io/vuln/SNYK-JS-PRISMJS-2404333

I think many of us on 3.x haven't upgraded because our packages/tools are not ESM compatible yet. There's little I can add to the existing discourse on this subject except to say that it shouldn't be trivialised when we have major parts of the ecosystem (think Jest, TypeScript) struggling to land support.

**Comment by wooorm** [comment]
Thanks

- TS + ESM should be mostly fine!
- At some point, you should probably switch to something other than Jest. There are better maintained and faster alternatives out there. See also https://github.com/facebook/jest/pull/11529#issuecomment-1027091448.
- I’m not saying things are trivial. I hope you understand that me maintaining multiple release lines isn’t either. That will stop at some point.
- This misses the point that `react-syntax-highlighter` isn’t maintained.

**Comment by wooorm** [comment]
Released!

**Comment by stof** [comment]
@wooorm I'm not using react-syntax-highlighter myself. I'm using Storybook, which uses react-syntax-highlighter

**Comment by stof** [comment]
And thanks for this backport.

**Comment by okonet** [comment]
Storybook will most probably switch from react-syntax-highlighter to something else in the future.

**Comment by wooorm** [comment]
I don’t exactly get what’s going on there, but it seems to reference Prism *actually running in the browser*? I don’t think this package, nor `react-syntax-highlighter`, cause that?
Can you point me to the exact problem there?

**Comment by okonet** [comment]
Hmm, I don't know where the "real" Prism JS came from but it was a race condition caused by it for sure.

**Comment by okonet** [comment]
I see the dependency here: https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/package.json

**Comment by wooorm** [comment]
There is some code to prevent Prism from doing weird stuff: https://github.com/wooorm/refractor/blob/c5744cb0c8df2309bab35c0505be51a2e37838f9/lib/core.js#L40-L56.
It could be that that’s not working (on a past version?)?

**Comment by okonet** [comment]
Yeah it seem like it. There is another approach which I really like: https://github.com/FormidableLabs/prism-react-renderer/blob/master/patches/prismjs%2B1.26.0.patch

Essentially it removes unused code instead of working around it. It also cuts the bundle size quite significantly. 

Maybe this approach could be considered in this repo as well?

**Comment by wooorm** [comment]
Landed that idea, thanks!
`react-syntax-highlighter` isn’t maintained actively though. You might still want to do that in house (and also potentially switch to lowlight/starry-night/etc)
